name: Continuous Integration

on:
  pull_request:

jobs:
  ci:
    runs-on: monline-generic
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Cache mypy
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: src/.mypy_cache/
          key: ${{ runner.os }}-mypy

      - name: Start Environment
        run: |
          set -ex
          make env-start
          make install-ci-requirements

      - name: Check Types
        run: make check-types

      - name: Check Style
        run: make check-style

      - name: Check Format
        run: make check-format

      - name: Run Tests
        run: make test

      - name: Clean Environment
        if: ${{ always() }}
        run: make env-destroy
